<a href="https://colab.research.google.com/github/shinae1023/AML_project/blob/main/earlyexit_stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/shinae1023/AML_project

Cloning into 'AML_project'...
remote: Enumerating objects: 289, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 289 (delta 1), reused 3 (delta 0), pack-reused 284 (from 2)
Receiving objects: 100% (289/289), 451.36 MiB | 17.80 MiB/s, done.
Resolving deltas: 100% (12/12), done.
Updating files: 100% (259/259), done.
[Errno 2] No such file or directory: 'earlyexitnet'
/content

In [2]:
!git clone https://github.com/biggsbenjamin/earlyexitnet
%cd earlyexitnet

Cloning into 'earlyexitnet'...
remote: Enumerating objects: 953, done.
remote: Counting objects: 100% (215/215), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 953 (delta 104), reused 168 (delta 76), pack-reused 738 (from 2)
Receiving objects: 100% (953/953), 84.70 MiB | 13.00 MiB/s, done.
Resolving deltas: 100% (496/496), done.
/content/earlyexitnet

In [3]:
!apt-get update
!apt-get install protobuf-compiler libprotoc-dev

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:2 https://cli.github.com/packages stable InRelease
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1,581 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [95.6 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [2,646 kB]
Get:9 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:11 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,355 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,295 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [7,070 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,294 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,602 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,947 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [86.4 kB]
Get:19 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [3,020 kB]
Get:20 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [77.8 kB]
Hit:21 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:22 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:23 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.2 MB]
Fetched 42.1 MB in 4s (9,698 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
protobuf-compiler is already the newest version (3.12.4-1ubuntu7.22.04.6).
The following additional packages will be installed:
  libprotobuf-dev libprotobuf-lite23
The following NEW packages will be installed:
  libprotobuf-dev libprotobuf-lite23 libprotoc-dev
0 upgraded, 3 newly installed, 0 to remove and 66 not upgraded.
Need to get 2,555 kB of archives.
After this operation, 19.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotobuf-lite23 amd64 3.12.4-1ubuntu7.22.04.6 [209 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotobuf-dev amd64 3.12.4-1ubuntu7.22.04.6 [1,347 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libprotoc-dev amd64 3.12.4-1ubuntu7.22.04.6 [999 kB]
Fetched 2,555 kB in 0s (44.5 MB/s)
Selecting previously unselected package libprotobuf-lite23:amd64.
(Reading database ... 122363 files and directories currently installed.)
Preparing to unpack .../libprotobuf-lite23_3.12.4-1ubuntu7.22.04.6_amd64.deb ...
Unpacking libprotobuf-lite23:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Selecting previously unselected package libprotobuf-dev:amd64.
Preparing to unpack .../libprotobuf-dev_3.12.4-1ubuntu7.22.04.6_amd64.deb ...
Unpacking libprotobuf-dev:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Selecting previously unselected package libprotoc-dev:amd64.
Preparing to unpack .../libprotoc-dev_3.12.4-1ubuntu7.22.04.6_amd64.deb ...
Unpacking libprotoc-dev:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Setting up libprotobuf-lite23:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Setting up libprotobuf-dev:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Setting up libprotoc-dev:amd64 (3.12.4-1ubuntu7.22.04.6) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

In [4]:
!pip install .

Processing /content/earlyexitnet
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting onnx (from Early_Exit_Networks==0.0.1)
  Downloading onnx-1.21.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (8.5 kB)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (5.29.6)
Collecting onnxruntime (from Early_Exit_Networks==0.0.1)
  Downloading onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting onnxoptimizer (from Early_Exit_Networks==0.0.1)
  Downloading onnxoptimizer-0.4.2-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.8.2 in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (0.25.0+cu128)
Collecting onnxsim (from Early_Exit_Networks==0.0.1)
  Downloading onnxsim-0.6.3-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (1.6.1)
Collecting fxpmath (from Early_Exit_Networks==0.0.1)
  Downloading fxpmath-0.4.10-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (4.67.3)
Collecting pylint>=3.3.3 (from Early_Exit_Networks==0.0.1)
  Downloading pylint-4.0.5-py3-none-any.whl.metadata (12 kB)
Collecting mypy>=1.14.1 (from Early_Exit_Networks==0.0.1)
  Downloading mypy-2.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.3 kB)
Collecting black (from Early_Exit_Networks==0.0.1)
  Downloading black-26.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.1/95.1 kB 10.3 MB/s eta 0:00:00
Requirement already satisfied: matplotlib>=3.10 in /usr/local/lib/python3.12/dist-packages (from Early_Exit_Networks==0.0.1) (3.10.0)
Collecting pandas==2.2.3 (from Early_Exit_Networks==0.0.1)
  Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 10.8 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->Early_Exit_Networks==0.0.1) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->Early_Exit_Networks==0.0.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.3->Early_Exit_Networks==0.0.1) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.10->Early_Exit_Networks==0.0.1) (3.3.2)
Requirement already satisfied: typing_extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from mypy>=1.14.1->Early_Exit_Networks==0.0.1) (4.15.0)
Collecting mypy_extensions>=1.0.0 (from mypy>=1.14.1->Early_Exit_Networks==0.0.1)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting pathspec>=1.0.0 (from mypy>=1.14.1->Early_Exit_Networks==0.0.1)
  Downloading pathspec-1.1.1-py3-none-any.whl.metadata (14 kB)
Collecting librt>=0.11.0 (from mypy>=1.14.1->Early_Exit_Networks==0.0.1)
  Downloading librt-0.11.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Collecting ast-serialize<1.0.0,>=0.3.0 (from mypy>=1.14.1->Early_Exit_Networks==0.0.1)
  Downloading ast_serialize-0.5.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.3 kB)
Collecting astroid<=4.1.dev0,>=4.0.2 (from pylint>=3.3.3->Early_Exit_Networks==0.0.1)
  Downloading astroid-4.0.4-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: dill>=0.3.6 in /usr/local/lib/python3.12/dist-packages (from pylint>=3.3.3->Early_Exit_Networks==0.0.1) (0.3.8)
Collecting isort!=5.13,<9,>=5 (from pylint>=3.3.3->Early_Exit_Networks==0.0.1)
  Downloading isort-8.0.1-py3-none-any.whl.metadata (11 kB)
Collecting mccabe<0.8,>=0.6 (from pylint>=3.3.3->Early_Exit_Networks==0.0.1)
  Downloading mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.12/dist-packages (from pylint>=3.3.3->Early_Exit_Networks==0.0.1) (4.9.6)
Requirement already satisfied: tomlkit>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from pylint>=3.3.3->Early_Exit_Networks==0.0.1) (0.13.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (3.29.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch->Early_Exit_Networks==0.0.1) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch->Early_Exit_Networks==0.0.1) (1.5.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black->Early_Exit_Networks==0.0.1) (8.3.3)
Collecting pytokens~=0.4.0 (from black->Early_Exit_Networks==0.0.1)
  Downloading pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: ml_dtypes>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from onnx->Early_Exit_Networks==0.0.1) (0.5.4)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime->Early_Exit_Networks==0.0.1) (25.12.19)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from onnxsim->Early_Exit_Networks==0.0.1) (13.9.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->Early_Exit_Networks==0.0.1) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->Early_Exit_Networks==0.0.1) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.3->Early_Exit_Networks==0.0.1) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->Early_Exit_Networks==0.0.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->Early_Exit_Networks==0.0.1) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->onnxsim->Early_Exit_Networks==0.0.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->onnxsim->Early_Exit_Networks==0.0.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->onnxsim->Early_Exit_Networks==0.0.1) (0.1.2)
Downloading pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 149.3 MB/s eta 0:00:00
Downloading mypy-2.1.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 143.7 MB/s eta 0:00:00
Downloading pylint-4.0.5-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.7/536.7 kB 46.7 MB/s eta 0:00:00
Downloading black-26.5.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 100.1 MB/s eta 0:00:00
Downloading fxpmath-0.4.10-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.1/53.1 kB 6.3 MB/s eta 0:00:00
Downloading onnx-1.21.0-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (17.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 133.4 MB/s eta 0:00:00
Downloading onnxoptimizer-0.4.2-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 71.8 MB/s eta 0:00:00
Downloading onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 127.8 MB/s eta 0:00:00
Downloading onnxsim-0.6.3-cp312-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 95.5 MB/s eta 0:00:00
Downloading ast_serialize-0.5.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 85.0 MB/s eta 0:00:00
Downloading astroid-4.0.4-py3-none-any.whl (276 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 276.4/276.4 kB 33.6 MB/s eta 0:00:00
Downloading isort-8.0.1-py3-none-any.whl (89 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 11.7 MB/s eta 0:00:00
Downloading librt-0.11.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (513 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 513.1/513.1 kB 48.8 MB/s eta 0:00:00
Downloading mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading pathspec-1.1.1-py3-none-any.whl (57 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 7.2 MB/s eta 0:00:00
Downloading pytokens-0.4.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (269 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 30.6 MB/s eta 0:00:00
Building wheels for collected packages: Early_Exit_Networks
  Building wheel for Early_Exit_Networks (pyproject.toml) ... done
  Created wheel for Early_Exit_Networks: filename=early_exit_networks-0.0.1-py3-none-any.whl size=59021 sha256=6ccbd74257a307cb8dac40c5cc2fddab48d66e2a75e1f19cceee1319465d5ba5
  Stored in directory: /tmp/pip-ephem-wheel-cache-65yozmvv/wheels/0a/49/d5/ba1c1ef4a6c4497e4e9d847ca3ad262566f0eaec34ecac61a9
Successfully built Early_Exit_Networks
Installing collected packages: pytokens, pathspec, onnxruntime, mypy_extensions, mccabe, librt, isort, fxpmath, astroid, ast-serialize, pylint, pandas, onnx, mypy, black, onnxsim, onnxoptimizer, Early_Exit_Networks
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
Successfully installed Early_Exit_Networks-0.0.1 ast-serialize-0.5.0 astroid-4.0.4 black-26.5.1 fxpmath-0.4.10 isort-8.0.1 librt-0.11.0 mccabe-0.7.0 mypy-2.1.0 mypy_extensions-1.1.0 onnx-1.21.0 onnxoptimizer-0.4.2 onnxruntime-1.26.0 onnxsim-0.6.3 pandas-2.2.3 pathspec-1.1.1 pylint-4.0.5 pytokens-0.4.1

In [11]:
!python -m earlyexitnet.cli -m b_lenet_se -d mnist -mp /content/AML_project/shinae/outputs/b_lenet_se/pre_Trn_bb_2026-05-21_070236/pretrn-joint-e26-2026-05-21_070702.pth -t1 0 -entr 0 -tr 0.1 2.0 -ts 0.1 -bste 500 -np /content/AML_project/shinae/outputs/b_lenet_se/range_notes -gpu 0 -nw 2 -cf 0

Model done: b_lenet_se
Model: b_lenet_se
Loss default function set
Setting up for testing
Device: cuda:0
Number of workers: 2
pin memory = True
100% 9.91M/9.91M [00:01<00:00, 5.45MB/s]
100% 28.9k/28.9k [00:00<00:00, 128kB/s]
100% 1.65M/1.65M [00:01<00:00, 1.24MB/s]
100% 4.54k/4.54k [00:00<00:00, 18.3MB/s]
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:157: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  rt_string = dt.utcfromtimestamp(timedelta(seconds=int(running_time)).total_seconds()).strftime("%M:%S")
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:158: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  tt_string = dt.utcfromtimestamp(timedelta(seconds=total_time).total_seconds()).strftime("%M:%S")

Running test 0/18, thresh: 0.1 		 [00:00/00:00]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:01<00:00, 5959.75samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9263, 0.0737]
Accuracy: [0.9985965669869373, 0.8602442333785617]
Total Accuracy: 0.988400
########
Total Accuracy: [0.985, 0.9878]

Running test 1/18, thresh: 0.2 		 [00:01/00:30]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17322.24samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9489, 0.0511]
Accuracy: [0.9975761407946043, 0.8258317025440313]
Total Accuracy: 0.988800
########
Total Accuracy: [0.985, 0.9878]

Running test 2/18, thresh: 0.30000000000000004 		 [00:02/00:20]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17174.22samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.96, 0.04]
Accuracy: [0.996875, 0.79]
Total Accuracy: 0.988600
########
Total Accuracy: [0.985, 0.9878]

Running test 3/18, thresh: 0.4 		 [00:02/00:17]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16952.13samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.969, 0.031]
Accuracy: [0.996078431372549, 0.7645161290322581]
Total Accuracy: 0.988900
########
Total Accuracy: [0.985, 0.9878]

Running test 4/18, thresh: 0.5 		 [00:03/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17378.71samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9761, 0.0239]
Accuracy: [0.9946726769798176, 0.7531380753138075]
Total Accuracy: 0.988900
########
Total Accuracy: [0.985, 0.9878]

Running test 5/18, thresh: 0.6 		 [00:04/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17267.30samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9822, 0.0178]
Accuracy: [0.9935858277336591, 0.7078651685393258]
Total Accuracy: 0.988500
########
Total Accuracy: [0.985, 0.9878]

Running test 6/18, thresh: 0.7000000000000001 		 [00:04/00:13]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16912.38samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9889, 0.0111]
Accuracy: [0.9916068358782486, 0.6756756756756757]
Total Accuracy: 0.988100
########
Total Accuracy: [0.985, 0.9878]

Running test 7/18, thresh: 0.8 		 [00:05/00:13]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16540.42samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9935, 0.0065]
Accuracy: [0.9897332662304983, 0.7076923076923077]
Total Accuracy: 0.987900
########
Total Accuracy: [0.985, 0.9878]

Running test 8/18, thresh: 0.9 		 [00:05/00:13]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17003.97samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9956, 0.0044]
Accuracy: [0.9883487344314986, 0.6590909090909091]
Total Accuracy: 0.986900
########
Total Accuracy: [0.985, 0.9878]

Running test 9/18, thresh: 1.0 		 [00:06/00:12]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17279.62samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9969, 0.0031]
Accuracy: [0.9876617514294312, 0.7419354838709677]
Total Accuracy: 0.986900
########
Total Accuracy: [0.985, 0.9878]

Running test 10/18, thresh: 1.1 		 [00:06/00:12]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16332.90samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9987, 0.0013]
Accuracy: [0.986081906478422, 0.8461538461538461]
Total Accuracy: 0.985900
########
Total Accuracy: [0.985, 0.9878]

Running test 11/18, thresh: 1.2000000000000002 		 [00:07/00:12]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16953.94samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9991, 0.0009]
Accuracy: [0.9856871184065659, 1.0]
Total Accuracy: 0.985700
########
Total Accuracy: [0.985, 0.9878]

Running test 12/18, thresh: 1.3000000000000003 		 [00:08/00:12]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16938.28samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9995, 0.0005]
Accuracy: [0.9853926963481741, 1.0]
Total Accuracy: 0.985400
########
Total Accuracy: [0.985, 0.9878]

Running test 13/18, thresh: 1.4000000000000001 		 [00:08/00:12]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17265.00samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9997, 0.0003]
Accuracy: [0.9852955886766029, 1.0]
Total Accuracy: 0.985300
########
Total Accuracy: [0.985, 0.9878]

Running test 14/18, thresh: 1.5000000000000002 		 [00:09/00:11]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16855.33samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9999, 0.0001]
Accuracy: [0.9850985098509851, 1.0]
Total Accuracy: 0.985100
########
Total Accuracy: [0.985, 0.9878]

Running test 15/18, thresh: 1.6 		 [00:09/00:11]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16339.90samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9999, 0.0001]
Accuracy: [0.9850985098509851, 1.0]
Total Accuracy: 0.985100
########
Total Accuracy: [0.985, 0.9878]

Running test 16/18, thresh: 1.7000000000000002 		 [00:10/00:11]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17013.24samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9999, 0.0001]
Accuracy: [0.9850985098509851, 1.0]
Total Accuracy: 0.985100
########
Total Accuracy: [0.985, 0.9878]

Running test 17/18, thresh: 1.8000000000000003 		 [00:11/00:11]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 16757.77samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9999, 0.0001]
Accuracy: [0.9850985098509851, 1.0]
Total Accuracy: 0.985100
########
Total Accuracy: [0.985, 0.9878]

Running test 18/18, thresh: 1.9000000000000001 		 [00:11/00:11]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 17050.50samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
/usr/local/lib/python3.12/dist-packages/earlyexitnet/tools.py:300: RuntimeWarning: invalid value encountered in divide
  self.avg_vals = self.val_bins / divisor
Exit percentages: [1.0, 0.0]
Accuracy: [0.985, nan]
Total Accuracy:  nan
########
Total Accuracy: [0.985, 0.9878]
Storing the test results at /content/AML_project/shinae/outputs/b_lenet_se/b_lenet_se_multiple_2026-05-24_041227.json

In [15]:
!python -m earlyexitnet.cli -m b_alexnet_cifar -d cifar10 -mp /content/AML_project/shinae/outputs/b_alexnet_cifar/pre_Trn_bb_2026-05-21_070918/pretrn-joint-e29-2026-05-21_073727.pth -t1 0 0 -entr 0 0 -tr 0.1 2.0 -ts 0.1 -bste 500 -np /content/AML_project/shinae/outputs/b_alexnet_cifar/range_notes/ -gpu 0 -nw 2 -cf 0

Model done: b_alexnet_cifar
Model: b_alexnet_cifar
Loss default function set
Setting up for testing
Device: cuda:0
Number of workers: 2
pin memory = True
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:157: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  rt_string = dt.utcfromtimestamp(timedelta(seconds=int(running_time)).total_seconds()).strftime("%M:%S")
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:158: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  tt_string = dt.utcfromtimestamp(timedelta(seconds=total_time).total_seconds()).strftime("%M:%S")

Running test 0/18, thresh: 0.1 		 [00:00/00:00]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:01<00:00, 8335.74samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.1548, 0.154, 0.846]
Accuracy: [0.9877260981912145, 0.974025974025974, 0.7378250591016549]
Total Accuracy: 0.927100
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 1/18, thresh: 0.2 		 [00:01/00:21]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13488.60samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.2334, 0.1711, 0.8289]
Accuracy: [0.9815766923736076, 0.9497369959088252, 0.739413680781759]
Total Accuracy: 1.004500
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 2/18, thresh: 0.30000000000000004 		 [00:01/00:17]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13011.00samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.2933, 0.1802, 0.8198]
Accuracy: [0.9727241732015002, 0.9273029966703663, 0.7437179799951208]
Total Accuracy: 1.062100
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 3/18, thresh: 0.4 		 [00:02/00:16]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12769.81samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.3469, 0.184, 0.816]
Accuracy: [0.9645430959930816, 0.8956521739130435, 0.7488970588235294]
Total Accuracy: 1.110500
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 4/18, thresh: 0.5 		 [00:03/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12986.02samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.3985, 0.1865, 0.8135]
Accuracy: [0.9515683814303638, 0.8707774798927614, 0.7542716656422864]
Total Accuracy: 1.155200
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 5/18, thresh: 0.6 		 [00:04/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13382.45samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.4491, 0.1888, 0.8112]
Accuracy: [0.9365397461589846, 0.8426906779661016, 0.758629191321499]
Total Accuracy: 1.195100
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 6/18, thresh: 0.7000000000000001 		 [00:05/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13647.00samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.5048, 0.1852, 0.8148]
Accuracy: [0.9193740095087163, 0.8072354211663066, 0.7673048600883653]
Total Accuracy: 1.238800
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 7/18, thresh: 0.8 		 [00:05/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13483.52samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.5641, 0.18, 0.82]
Accuracy: [0.898244992022691, 0.7716666666666666, 0.776829268292683]
Total Accuracy: 1.282600
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 8/18, thresh: 0.9 		 [00:06/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13377.93samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.6211, 0.1714, 0.8286]
Accuracy: [0.8773144421188215, 0.7380396732788798, 0.7845763939174512]
Total Accuracy: 1.321500
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 9/18, thresh: 1.0 		 [00:07/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13001.99samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.6771, 0.1588, 0.8412]
Accuracy: [0.8545266578053463, 0.7052896725440806, 0.7898240608654303]
Total Accuracy: 1.355000
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 10/18, thresh: 1.1 		 [00:08/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13302.50samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.7296, 0.1446, 0.8554]
Accuracy: [0.8363486842105263, 0.6708160442600276, 0.7948328267477204]
Total Accuracy: 1.387100
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 11/18, thresh: 1.2000000000000002 		 [00:08/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13104.86samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.7808, 0.1293, 0.8707]
Accuracy: [0.8185194672131147, 0.6326372776488786, 0.7968301366716435]
Total Accuracy: 1.414700
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 12/18, thresh: 1.3000000000000003 		 [00:09/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13083.78samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.8332, 0.1059, 0.8941]
Accuracy: [0.8007681228996639, 0.5967894239848914, 0.7963315065428923]
Total Accuracy: 1.442400
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 13/18, thresh: 1.4000000000000001 		 [00:10/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13217.97samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.8774, 0.0833, 0.9167]
Accuracy: [0.7835650786414406, 0.5510204081632653, 0.7955710701429038]
Total Accuracy: 1.462700
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 14/18, thresh: 1.5000000000000002 		 [00:11/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12666.34samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9188, 0.0589, 0.9411]
Accuracy: [0.7681758815846756, 0.5212224108658744, 0.7891828711082776]
Total Accuracy: 1.479200
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 15/18, thresh: 1.6 		 [00:11/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12938.56samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9527, 0.0365, 0.9635]
Accuracy: [0.7556418599769077, 0.4684931506849315, 0.7842241826673586]
Total Accuracy: 1.492600
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 16/18, thresh: 1.7000000000000002 		 [00:12/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13143.61samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9738, 0.0215, 0.9785]
Accuracy: [0.7467652495378928, 0.46511627906976744, 0.7806847215125191]
Total Accuracy: 1.501100
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 17/18, thresh: 1.8000000000000003 		 [00:13/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12369.71samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9885, 0.0105, 0.9895]
Accuracy: [0.7402124430955994, 0.4666666666666667, 0.7774633653360283]
Total Accuracy: 1.505900
########
Total Accuracy: [0.7356, 0.7681, 0.774]

Running test 18/18, thresh: 1.9000000000000001 		 [00:14/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12886.26samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9963, 0.0036, 0.9964]
Accuracy: [0.7373281140218809, 0.4166666666666667, 0.7750903251706142]
Total Accuracy: 1.508400
########
Total Accuracy: [0.7356, 0.7681, 0.774]
Storing the test results at /content/AML_project/shinae/outputs/b_alexnet_cifar/range_notes/b_alexnet_cifar_multiple_2026-05-24_042108.json

In [13]:
!python -m earlyexitnet.cli -m resnet8_2ee -d cifar10 -mp /content/AML_project/shinae/outputs/resnet8_2ee/pre_Trn_bb_2026-05-21_073907/pretrn-joint-e27-2026-05-21_080552.pth -t1 0 -entr 0 -tr 0.1 2.0 -ts 0.1 -bste 500 -np /content/AML_project/shinae/outputs/resnet8_2ee/range_notes/ -gpu 0 -nw 2 -cf 0

Classif @ 0 linear dim: 512
Model done: resnet8_2ee
Model: resnet8_2ee
Loss default function set
Setting up for testing
Device: cuda:0
Number of workers: 2
pin memory = True
100% 170M/170M [02:39<00:00, 1.07MB/s]
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:157: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  rt_string = dt.utcfromtimestamp(timedelta(seconds=int(running_time)).total_seconds()).strftime("%M:%S")
/usr/local/lib/python3.12/dist-packages/earlyexitnet/cli.py:158: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  tt_string = dt.utcfromtimestamp(timedelta(seconds=total_time).total_seconds()).strftime("%M:%S")

Running test 0/18, thresh: 0.1 		 [00:00/00:00]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:01<00:00, 7842.90samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.115, 0.885]
Accuracy: [0.9852173913043478, 0.7742372881355932]
Total Accuracy: 0.798500
########
Total Accuracy: [0.7077, 0.7986]

Running test 1/18, thresh: 0.2 		 [00:01/00:23]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12467.17samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.1882, 0.8118]
Accuracy: [0.9776833156216791, 0.7568366592756837]
Total Accuracy: 0.798400
########
Total Accuracy: [0.7077, 0.7986]

Running test 2/18, thresh: 0.30000000000000004 		 [00:02/00:18]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13637.96samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.248, 0.752]
Accuracy: [0.9713709677419354, 0.7414893617021276]
Total Accuracy: 0.798500
########
Total Accuracy: [0.7077, 0.7986]

Running test 3/18, thresh: 0.4 		 [00:02/00:16]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13832.81samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.3009, 0.6991]
Accuracy: [0.9574609504818876, 0.7275067944500071]
Total Accuracy: 0.796700
########
Total Accuracy: [0.7077, 0.7986]

Running test 4/18, thresh: 0.5 		 [00:03/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13293.54samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.3556, 0.6444]
Accuracy: [0.9443194600674916, 0.7144630664183736]
Total Accuracy: 0.796200
########
Total Accuracy: [0.7077, 0.7986]

Running test 5/18, thresh: 0.6 		 [00:04/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13544.99samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.4089, 0.5911]
Accuracy: [0.9273661041819515, 0.7008966333953646]
Total Accuracy: 0.793500
########
Total Accuracy: [0.7077, 0.7986]

Running test 6/18, thresh: 0.7000000000000001 		 [00:05/00:15]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13353.94samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.4681, 0.5319]
Accuracy: [0.9040803247169408, 0.6865952246662906]
Total Accuracy: 0.788400
########
Total Accuracy: [0.7077, 0.7986]

Running test 7/18, thresh: 0.8 		 [00:05/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13757.78samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.53, 0.47]
Accuracy: [0.8824528301886793, 0.6668085106382978]
Total Accuracy: 0.781100
########
Total Accuracy: [0.7077, 0.7986]

Running test 8/18, thresh: 0.9 		 [00:06/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13577.73samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.5934, 0.4066]
Accuracy: [0.856757667677789, 0.6512543039842598]
Total Accuracy: 0.773200
########
Total Accuracy: [0.7077, 0.7986]

Running test 9/18, thresh: 1.0 		 [00:07/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13864.47samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.6518, 0.3482]
Accuracy: [0.8355323718932188, 0.6352670878805284]
Total Accuracy: 0.765800
########
Total Accuracy: [0.7077, 0.7986]

Running test 10/18, thresh: 1.1 		 [00:07/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13430.13samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.7093, 0.2907]
Accuracy: [0.8172846468349076, 0.6185070519435845]
Total Accuracy: 0.759500
########
Total Accuracy: [0.7077, 0.7986]

Running test 11/18, thresh: 1.2000000000000002 		 [00:08/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13695.52samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.7671, 0.2329]
Accuracy: [0.7952027115108852, 0.6015457277801631]
Total Accuracy: 0.750100
########
Total Accuracy: [0.7077, 0.7986]

Running test 12/18, thresh: 1.3000000000000003 		 [00:09/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13824.25samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.8176, 0.1824]
Accuracy: [0.7766634050880626, 0.587171052631579]
Total Accuracy: 0.742100
########
Total Accuracy: [0.7077, 0.7986]

Running test 13/18, thresh: 1.4000000000000001 		 [00:10/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13405.42samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.8677, 0.1323]
Accuracy: [0.7592485882217356, 0.5797430083144369]
Total Accuracy: 0.735500
########
Total Accuracy: [0.7077, 0.7986]

Running test 14/18, thresh: 1.5000000000000002 		 [00:10/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13140.75samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9135, 0.0865]
Accuracy: [0.7434044882320744, 0.5710982658959538]
Total Accuracy: 0.728500
########
Total Accuracy: [0.7077, 0.7986]

Running test 15/18, thresh: 1.6 		 [00:11/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 12855.26samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9451, 0.0549]
Accuracy: [0.7312453708602265, 0.5792349726775956]
Total Accuracy: 0.722900
########
Total Accuracy: [0.7077, 0.7986]

Running test 16/18, thresh: 1.7000000000000002 		 [00:12/00:14]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13713.51samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9688, 0.0312]
Accuracy: [0.7214079273327828, 0.5608974358974359]
Total Accuracy: 0.716400
########
Total Accuracy: [0.7077, 0.7986]

Running test 17/18, thresh: 1.8000000000000003 		 [00:13/00:13]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13841.83samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.9852, 0.0148]
Accuracy: [0.7138652050345108, 0.5540540540540541]
Total Accuracy: 0.711500
########
Total Accuracy: [0.7077, 0.7986]

Running test 18/18, thresh: 1.9000000000000001 		 [00:13/00:13]
Device: cuda:0, pin memory = True
Running on device: cuda:0
Test of length 20 starting:
100% 10000/10000 [00:00<00:00, 13400.55samples/s]
### TEST FINISHED ###
--- _thr_entropy ---
Exit percentages: [0.995, 0.005]
Accuracy: [0.7094472361809046, 0.62]
Total Accuracy: 0.709000
########
Total Accuracy: [0.7077, 0.7986]
Storing the test results at /content/AML_project/shinae/outputs/resnet8_2ee/range_notes/resnet8_2ee_multiple_2026-05-24_041705.json

In [17]:
import json
import glob
import os
import math
import pandas as pd
from IPython.display import display

def force_float(val):
    if val is None: return 0.0
    if isinstance(val, str) and val.lower() in ['nan', 'null', 'none']: return 0.0
    try:
        f = float(val)
        return 0.0 if math.isnan(f) else f
    except:
        return 0.0

# 변경된 경로 반영
models = [
    {"name": "LeNet (MNIST)", "path": "/content/AML_project/shinae/outputs/b_lenet_se/range_notes/*multiple*.json", "exits": 2},
    {"name": "AlexNet (CIFAR-10)", "path": "/content/AML_project/shinae/outputs/b_alexnet_cifar/range_notes/*multiple*.json", "exits": 3},
    {"name": "ResNet8 (CIFAR-10)", "path": "/content/AML_project/shinae/outputs/resnet8_2ee/range_notes/*multiple*.json", "exits": 2}
]

for m in models:
    json_files = glob.glob(m["path"])
    if not json_files:
        print(f"⚠️ {m['name']}의 JSON 스캔 파일을 찾을 수 없음. 경로를 확인하셈.")
        continue

    latest_json = max(json_files, key=os.path.getctime)

    with open(latest_json, "r") as f:
        data = json.load(f)

    test_vals = data.get("test_vals", [])
    if not test_vals: continue

    target_key = list(test_vals[0]["conf_metrics"].keys())[0]
    num_exits = m["exits"]
    latency_rows = []

    for i, item in enumerate(test_vals):
        metrics = item["conf_metrics"][target_key]

        # 주입된 인덱스를 바탕으로 올바른 Threshold 역산
        thr = 0.1 + (i * 0.1)

        exit_pc = [force_float(p) for p in metrics.get("exit_pc", [])]
        acc = force_float(metrics.get("combined_accuracy"))

        # NaN 결측치 수동 복구 연산
        if acc == 0.0:
            acc_list = metrics.get("accu_pc", [])
            calc_acc = 0.0
            for a, p in zip(acc_list, exit_pc):
                if force_float(p) > 0 and force_float(a) > 0:
                    calc_acc += force_float(a) * force_float(p)
            acc = calc_acc

        if acc > 0:
            avg_exit_layer = sum((j + 1) * pct for j, pct in enumerate(exit_pc))
            if avg_exit_layer == 0: avg_exit_layer = num_exits

            expected_saving = (1 - (avg_exit_layer / num_exits)) * 100
            approx_speedup = num_exits / avg_exit_layer

            latency_rows.append({
                "Threshold (S)": round(thr, 2),
                "Accuracy (%)": round(acc * 100, 2),
                "EE1 Ratio (%)": round(exit_pc[0] * 100, 2),
                "Avg Exit Layer": round(avg_exit_layer, 3),
                "Expected Saving (%)": round(expected_saving, 2),
                "Approx Speedup (x)": round(approx_speedup, 2)
            })

    if latency_rows:
        df = pd.DataFrame(latency_rows)
        df = df.drop_duplicates(subset=["Threshold (S)"]).reset_index(drop=True)

        print(f"\n📊 [출력 완료] {m['name']} 성능 통합 지표 테이블")
        display(df)

📊 [출력 완료] LeNet (MNIST) 성능 통합 지표 테이블

,Threshold (S),Accuracy (%),EE1 Ratio (%),Avg Exit Layer,Expected Saving (%),Approx Speedup (x)
0,0.1,98.84,92.63,1.074,46.31,1.86
1,0.2,98.88,94.89,1.051,47.45,1.90
2,0.3,98.86,96.00,1.040,48.00,1.92
3,0.4,98.89,96.90,1.031,48.45,1.94
4,0.5,98.89,97.61,1.024,48.80,1.95
5,0.6,98.85,98.22,1.018,49.11,1.97
6,0.7,98.81,98.89,1.011,49.44,1.98
7,0.8,98.79,99.35,1.006,49.68,1.99
8,0.9,98.69,99.56,1.004,49.78,1.99
9,1.0,98.69,99.69,1.003,49.84,1.99
10,1.1,98.59,99.87,1.001,49.93,2.00
11,1.2,98.57,99.91,1.001,49.96,2.00
12,1.3,98.54,99.95,1.000,49.98,2.00
13,1.4,98.53,99.97,1.000,49.98,2.00
14,1.5,98.51,99.99,1.000,49.99,2.00
15,1.6,98.51,99.99,1.000,49.99,2.00
16,1.7,98.51,99.99,1.000,49.99,2.00
17,1.8,98.51,99.99,1.000,49.99,2.00
18,1.9,98.50,100.00,1.000,50.00,2.00

📊 [출력 완료] AlexNet (CIFAR-10) 성능 통합 지표 테이블

,Threshold (S),Accuracy (%),EE1 Ratio (%),Avg Exit Layer,Expected Saving (%),Approx Speedup (x)
0,0.1,92.71,15.48,3.001,-0.03,1.00
1,0.2,100.45,23.34,3.062,-2.08,0.98
2,0.3,106.21,29.33,3.113,-3.77,0.96
3,0.4,111.05,34.69,3.163,-5.43,0.95
4,0.5,115.52,39.85,3.212,-7.07,0.93
5,0.6,119.51,44.91,3.260,-8.68,0.92
6,0.7,123.88,50.48,3.320,-10.65,0.90
7,0.8,128.26,56.41,3.384,-12.80,0.89
8,0.9,132.15,62.11,3.450,-14.99,0.87
9,1.0,135.50,67.71,3.518,-17.28,0.85
10,1.1,138.71,72.96,3.585,-19.50,0.84
11,1.2,141.47,78.08,3.651,-21.72,0.82
12,1.3,144.24,83.32,3.727,-24.24,0.80
13,1.4,146.27,87.74,3.794,-26.47,0.79
14,1.5,147.92,91.88,3.860,-28.66,0.78
15,1.6,149.26,95.27,3.916,-30.54,0.77
16,1.7,150.11,97.38,3.952,-31.74,0.76
17,1.8,150.59,98.85,3.978,-32.60,0.75
18,1.9,150.84,99.63,3.993,-33.09,0.75

📊 [출력 완료] ResNet8 (CIFAR-10) 성능 통합 지표 테이블

,Threshold (S),Accuracy (%),EE1 Ratio (%),Avg Exit Layer,Expected Saving (%),Approx Speedup (x)
0,0.1,79.85,11.50,1.885,5.75,1.06
1,0.2,79.84,18.82,1.812,9.41,1.10
2,0.3,79.85,24.80,1.752,12.40,1.14
3,0.4,79.67,30.09,1.699,15.04,1.18
4,0.5,79.62,35.56,1.644,17.78,1.22
5,0.6,79.35,40.89,1.591,20.45,1.26
6,0.7,78.84,46.81,1.532,23.40,1.31
7,0.8,78.11,53.00,1.470,26.50,1.36
8,0.9,77.32,59.34,1.407,29.67,1.42
9,1.0,76.58,65.18,1.348,32.59,1.48
10,1.1,75.95,70.93,1.291,35.46,1.55
11,1.2,75.01,76.71,1.233,38.36,1.62
12,1.3,74.21,81.76,1.182,40.88,1.69
13,1.4,73.55,86.77,1.132,43.38,1.77
14,1.5,72.85,91.35,1.087,45.67,1.84
15,1.6,72.29,94.51,1.055,47.26,1.90
16,1.7,71.64,96.88,1.031,48.44,1.94
17,1.8,71.15,98.52,1.015,49.26,1.97
18,1.9,70.90,99.50,1.005,49.75,1.99